FROM node:20-alpine AS test
WORKDIR /app
COPY . .
# TODO: Comment out for production so the scan node's keys are used
COPY forta.config.json ./forta.config.json
RUN npm ci
RUN npm run build
CMD ["npm", "test"]